#!/bin/bash
#
if [ $# -eq 0 ]; then
	echo "No arguments provided"
	exit 1
fi

DIRECTORY=$1

if [ ! -d "./"$DIRECTORY ]; then
	echo $DIRECTORY is not a valid directory
	exit 1
fi

python -m bootstrap.initialize -o $DIRECTORY"/options.yaml"
