#!/bin/bash
#
# Displays the users queue in a nice format
#
# Arg1: User id, default user id of caller

USERID=$1
if [ "$*" == "" ]; then
    USERID=$USER
fi

echo "Showing queue for: "$USERID

squeue -o "%.28j %.8T %.10M %.9l %.9P %.10i %.10R" -u $USERID
