#!/bin/bash
#
# Starts a simple http server to allow for 
# file exploration in your remote directory
# 
# Arg_1: port, default 8000

PORT=$1

echo $PORT

if [ "$*" == "" ]; then
    PORT=8000
fi

echo "Starting server on: https://localhost:"$PORT
python3 -m http.server $PORT >/dev/null

