#!/bin/bash

BATCHFILE=$1

if [ $# -eq 0 ]; then
    echo "No arguments provided"
    exit 1
fi

read -p "Name of job: "  job_name
echo "Running job $job_name!"

sbatch -J $job_name -o "slurm_"$job_name".txt" $BATCHFILE