#!/bin/bash
#
# Provides a prompt for job name upon submission of a SBATCH job
# SLURM output file will have same name 
# (OUTPUT FILES WILL BE OVERWRITTEN IF MULTIPLE JOBS ARE SUBMITTED WITH THE SAME NAME)
#
# Arg1: job_name, REQUIRED

BATCHFILE=$1

if [ $# -eq 0 ]; then
    echo "No arguments provided"
    exit 1
fi

read -p "Name of job: "  job_name
echo "Running job $job_name!"

sbatch -J $job_name -o "slurm/"$job_name".txt" $BATCHFILE